### ISSUE TITLE
requireAll does not require @type and should

### ISSUE THREAD

**Issue by azaroth42** [w3c/json-ld-framing#40] opened 2019-02-27 21:54 UTC
From discussion on the [mailing list](https://lists.w3.org/Archives/Public/public-linked-json/2019Feb/0018.html), it was noted that the `requireAll` flag does not actually require _all_, it requires everything other than `@id` and `@type`. 

The proposal arising is to make it actually require all of the asserted features, including `@type` and `@id`.

**Comment by dlongley** [comment] 2019-02-27 22:01
We might need to tweak the proposal a bit -- because right now I think `requireAll` would require `@type` if present (because when `@type` is present it is *always* required). The problem is that it doesn't require any of the *other* properties when `@type` is present. The proposal is to make it such that when `@type` is present, all of the *other* properties are also required.

**Comment by dlongley** [comment] 2019-02-27 22:02
Or, more generally, when `requireAll` is `true`, all specific properties must be present or there is no match. There is no special treatment of `@type` or `@id`.

**Comment by iherman** [comment] 2019-03-02 08:41
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-03-01-json-ld#section3).

- `RESOLVED:  If requireAll is present, then all keys in the frame are used to determine a match, including @type and @id`
<details><summary><i class="differentiate">View the transcript</i></summary>
3. requireAll does not require @type and should<br/>
Rob Sanderson: <a href="https://github.com/w3c/json-ld-framing/issues/40">https://github.com/w3c/json-ld-framing/issues/40</a><br/>
Gregg Kellogg: we added require all flag that does not work the way people expect. People expected it to literally mean ‘require all’ not a combination of if/or<br/>
Ivan Herman: can we close the issue?<br/>
Gregg Kellogg: not close but we agree to move to approve it<br/>
Proposed resolution: IF requireAll is present, then all keys in the frame are used to determine a match, including @type and @id (Rob Sanderson)<br/>
Gregg Kellogg: seems logical to be if require all is present then all keys in the frame are used to determine that<br/>
Gregg Kellogg: +1<br/>
Dave Longley: +1<br/>
Rob Sanderson: +1<br/>
Benjamin Young: +1<br/>
Jeff Mixter: +1<br/>
Ivan Herman: +1<br/>
Tim Cole: +1<br/>
Harold Solbrig: +1<br/>
Simon Steyskal: +1<br/>
David Newbury: +1<br/>
David I. Lehn: +1<br/>
Resolution #2: If requireAll is present, then all keys in the frame are used to determine a match, including @type and @id<br/>
</details>

**Closed** 2019-04-24 16:12 UTC
Labels: spec:bug, spec:editorial
